version: '3.5'

services:
  account:
    build: ./account
    container_name: x-account
    networks:
      - ser-network

  game:
    build: ./game
    container_name: x-game
    networks:
      - ser-network

  hall:
    build: ./hall
    container_name: x-hall
    networks:
      - ser-network

networks:
  ser-network:
    name: x-ser-network
